// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB154NmyP-1nBsOxmpaQqyuIoIwfxTQL40',
    appId: '1:12387052869:web:0d920648ad6aa24083e22c',
    messagingSenderId: '12387052869',
    projectId: 'quikhyr',
    authDomain: 'quikhyr.firebaseapp.com',
    databaseURL: 'https://quikhyr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quikhyr.appspot.com',
    measurementId: 'G-B5ZTGGZ1W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGglKv24u9fZTjpWnBq_xszQTFN_Qs-_U',
    appId: '1:12387052869:android:47d07852427ce97d83e22c',
    messagingSenderId: '12387052869',
    projectId: 'quikhyr',
    databaseURL: 'https://quikhyr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quikhyr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6WpfVBzJACFcxtz2TZLCS9u0kzLlRgIQ',
    appId: '1:12387052869:ios:d5a14a43849706d283e22c',
    messagingSenderId: '12387052869',
    projectId: 'quikhyr',
    databaseURL: 'https://quikhyr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quikhyr.appspot.com',
    iosBundleId: 'com.example.quikhyr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6WpfVBzJACFcxtz2TZLCS9u0kzLlRgIQ',
    appId: '1:12387052869:ios:36000cecc594e84083e22c',
    messagingSenderId: '12387052869',
    projectId: 'quikhyr',
    databaseURL: 'https://quikhyr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quikhyr.appspot.com',
    iosBundleId: 'com.example.quikhyr.RunnerTests',
  );
}
